### ISSUE TITLE
timezone incorrect procession

### ISSUE THREAD

**Issue by vkogan2005** [Lefey/ad_narodmon_sender#7]
Several lines should be added to narodmon_sender.py: 

import pytz
timezone = pytz.timezone("Europe/Moscow") - that's my case, probably you need to get right timezone from HA (dont' know yet how to do it) 

And one line needs to be updated: self.run_every(self.send_data, datetime.datetime.now(tz = timezone) + datetime.timedelta(seconds=2), 360) 

Otherwise AppDaemon schedules incorrect time to run this script.

**Comment by Lefey** [comment]
Hi!
Thank you so much for your suggested solution! Your recommendations for adding the pytz library is a great idea 👍
Also, there is other way to address the issue is to set the correct time zone in the AppDaemon config, but I believe your proposed solution is even better. It will work consistently, regardless of the time zone specified in the system and AppDaemon settings.

**Comment by Lefey** [comment]
Added pytz with default utc zone 5812590
